### ISSUE TITLE
Make proper release plan

### ISSUE THREAD

**Issue by kukovecz** [IoT-Inspector/unblob#111]
Establish a clear way of doing releases from this project.

Some ideas (without any kind of order / importance whatsoever):
* Push docker image to public registry with proper tagging / labeling? (#36 follow-up)
* Same with standalone binary? (#102 follow-up)
* Publish (pypi) package? (#101 follow-up)
* etc?!

**Comment by kissgyorgy** [comment]
I would not think about this too much. We already know what our bigger milestones are: https://github.com/IoT-Inspector/unblob/milestones the points you mentioned should be in GitHub pipeline which will run on Git tag pushes and we will make releases whenever needed.

**Comment by kukovecz** [comment]
Yes, that is my point. I am not debating about WHAT the content of the releases should be, we have the milestones for that. But the technicalities of HOW should we do the releases. I mean, yeah, with some kind of pipelines you mentioned, but what should that pipelines do (see the ticket's description), where should the artifacts be (for example if we release a docker image, which registry should it be in, etc.)

**Comment by kissgyorgy** [comment]
I don't think we need to implement anything complicated. When we release the package to https://pypi.org, we will release it with Poetry. When we will do the standalone ELF executable, we will use GitHub releases page with attached checksums and that's it. The technical details can be decided when we implement these separately.
