### ISSUE TITLE
Inexact padding calculation on specific TAR files

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#118]
The offset computation we came up with in the TarHandler at `_get_tar_end_offset` is inexact for specific files.

I surmise it has to do with block padding and block alignment. Without a fix, unblob finds the end offset past the file and discard the chunk.

I can provide a sample internally if someone wants to work on this:

```
sha1sum /tmp/firmware.img 
fc910cc004254fda5eef27c88f943296d3df967e  /tmp/firmware.img
```

**Comment by vlaci** [comment]
I can look into it tomorrow

**Comment by vlaci** [comment]
I've experimented a bit, and dove into GNU tar's source and found out that `tarfile.RECORDSIZE` is just `tarfile.BLOCKSIZE` times what GNU tar calls as `--blocking-factor`. It's default value is `20` matching the Python implementation, but it is not something we should expect and certainly not set in stone. It can be smaller and even greater.

It is not the full story as the example file here is properly aligned to consist of 2 tar blocks, however it ends with only 384 padding zeroes.

Regarding the final zeroes `info tar` says:

> At the end of the archive file there are two 512-byte blocks
> filled with binary zeros as an end-of-file marker.  A reasonable system
> should write such end-of-file marker at the end of an archive, but must
> not assume that such a block exists when reading an archive.  In
> particular GNU 'tar' always issues a warning if it does not encounter
> it.

Interestingly this file does not issue a warning when extracted by GNU tar, so this end block thingy can be considered optional?
On the other hand we shouldn't fail on tar files missing this feature as the documentation says `reasonable systems shouldn't expect its existence`.

So my proposal now is to either:
* guess the last block's end, then count down any as many 512 byte zero blocks as there are. 
* extract files without final zero blocks
