### ISSUE TITLE
Extractor version handling - documentation

### ISSUE THREAD

**Issue by kukovecz** [IoT-Inspector/unblob#134]
#113  Introduces the ability to check if the current environment has the needed extractors installed for each handler.

However, the CLI of these extractors can be varying based on the version - some subcommands / options may only be available from/to a specific version. Right now, we do not check if the right version of the extractor is installed, only that the extractor itself is available.

So, check the installed extractor version and match it with the handler.

**Comment by kukovecz** [comment]
#131 also mentions this problem in great detail specific to `7z`.

**Comment by kissgyorgy** [comment]
We agreed to only document this for v1.0.

**Comment by vlaci** [comment]
Fixed in #251
