### ISSUE TITLE
Missing support for non-standard squashfs v4 big endian

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#159]
By definition, squashfs version 4.0 is fixed little-endian. However, some implementations do not follow the standard and we therefore need to add support for such filesystems.

Note that we cannot land this modification until we have our own fork of unsquashfs that can extract version 4.0 in big endian.

A branch with proper detection and mapping is available at https://github.com/IoT-Inspector/unblob/tree/feat-squashfs-v4-be, but the PR won't be created until I get unsquashfs to work.

A sample is available if you want, ask for `4e3fd06476376ec13c101d0362e06b6758288220`

**Comment by vlaci** [comment]
We agreed in not supporting this format for v1.0

**Comment by QKaiser** [comment]
Closing this here and opening a ticket in our fork of sasquatch so we can work independently - https://github.com/IoT-Inspector/sasquatch/issues/2
