### ISSUE TITLE
Support handlers without extraction methods

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#166]
We plan on writing handlers for executable formats such as PE or ELF. It's useful to carve them out of larger chunks but there is no extraction or decompression method required given that the carved out file is all there is to it.

Unblob should support handlers with a `make_extract_command` function that is either undefined or returns an empty list. Whichever solution is best.

**Comment by vlaci** [comment]
I think handlers should expose a method doing the extraction, or returning an `Extractor` object that could be used to do the extraction instead of the the current method which also has some quirks, e. g. #147
