### ISSUE TITLE
Uncaught PermissionError in unblob on malformed JFFS2 filesystems

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#190]
This issue was identified through mutation fuzzing (valid integration test files run through radamsa).

The JFFS2 filesystem has been corrupted in such a way that one of the extracted files is missing the read bit permission for our user, which leads to a permission deny:

```
Traceback (most recent call last):
  File "/home/quentin/unblob/unblob/cli.py", line 99, in main
    cli.invoke(ctx)
  File "/home/quentin/.cache/pypoetry/virtualenvs/unblob-U71Ryf-L-py3.8/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/quentin/.cache/pypoetry/virtualenvs/unblob-U71Ryf-L-py3.8/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/quentin/unblob/unblob/cli.py", line 81, in cli
    process_file(root, path, extract_root, max_depth=depth)
  File "/home/quentin/unblob/unblob/processing.py", line 62, in process_file
    process_file(
  File "/home/quentin/unblob/unblob/processing.py", line 39, in process_file
    process_file(root, path, extract_root, max_depth, current_depth + 1)
  File "/home/quentin/unblob/unblob/processing.py", line 39, in process_file
    process_file(root, path, extract_root, max_depth, current_depth + 1)
  File "/home/quentin/unblob/unblob/processing.py", line 52, in process_file
    with path.open("rb") as file:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/quentin/unblob/010a2f2e45cf500ad9087e730542099049f442fc.bin_extract/0-392.jffs2_new_extract/fs_1/apple.txt'
```

This is what the extraction directory looks like:

```
total 20
drwxrwxr-x 2 quentin quentin 4096 Jan 21 11:08 .
drwxrwxr-x 3 quentin quentin 4096 Jan 21 11:08 ..
--w-rw-r-- 1 quentin quentin   26 Jan 21 11:08 apple.txt
-rw--w-r-x 1 quentin quentin    7 Jan 21 11:08 banana.txt
-rw-rw-r-- 1 quentin quentin    7 Jan 21 11:08 cherry.txt
```

We can see that the read bit is missing from apple.txt. Interestingly, JFFS2 files can either be world RW or world RWX per the standard (there is only an executable bit that is set or not), so it's a bug in jefferson. **WRONG**: confused it with RomFS :)

We should still have a discussion on how to handle these kinds of situation in unblob. I see two ways of fixing this:
- we catch the PermissionError and do not scan the file
- we catch the PermissionError and, if we are the file owner, we grant us read permission on that file

Permission checks should also take upper directories into consideration as they may end up missing the read flag once created by one of our external extractors, and permissions should be fixed too.

So far I've only seen it happen in JFFS2 handler, due to a bug in jefferson.

**Comment by QKaiser** [comment]
I'll work on this once we get fixes into jefferson. Happy to get your inputs @vlaci  @kukovecz regarding how we should handle the situation (fix permission or disregard the file) 🤓

**Comment by QKaiser** [comment]
I confused RomFS and JFFS2, it's entirely possible to get these permissions encoded in JFFS2 so it's not a bug in jefferson. Let's talk !

**Comment by vlaci** [comment]
I think we should normalize file ownership information in a similarly to symlink targets. The original unaltered permission info should be part of the extraction metadata.

**Comment by QKaiser** [comment]
Agreed. Let's use Linux's default behavior for non-root users (umask set to `022`) so folder permission set to `775: rwxrwxr-x` and file permissions to `664: rw-rw-r--` when normalizing permissions.
