### ISSUE TITLE
Optimize yara timeout value

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#201]
When running unblob on very large files, we can reach a timeout condition triggered by Yara due to the fixed timeout of 60 seconds set in https://github.com/IoT-Inspector/unblob/blob/main/unblob/finder.py#L127:

```python
def search_yara_patterns(
    yara_rules: yara.Rule, handler_map: Dict[str, Handler], full_path: Path
) -> List[YaraMatchResult]:
    """Search with the compiled YARA rules and identify the handler which defined the rule."""
    # YARA uses a memory mapped file internally when given a path
    yara_matches: List[yara.Match] = yara_rules.match(str(full_path), timeout=60)
```

This timeout value is not optimal for large files.

**Comment by vlaci** [comment]
Also, this should be covered in #100, as there can be potentially inefficient Yara rules as well.

**Comment by vlaci** [comment]
Sidenote: do we really want to have a timeout feature in the first place? I'd like to see real-world firmwares causing significant slowdowns in the first place. Also, I don't think we should set a timeout for Yara as well.

**Comment by QKaiser** [comment]
Challenge accepted !

**Comment by QKaiser** [comment]
I edited the issue title and description. Ideally we should benchmark our ruleset against random files of different sizes and derive an optimal timeout value from it.

One limitation is that we can't make any assumptions about the resources of the machine unblob is running on, so there has to be some "breathing space" added to that timeout.

**Comment by vlaci** [comment]
Do we need a timeout at all at this level? Given that all our rules are well-behaving and don't cause backtracking in the regular expression engine, they all should scale linearly with the file-size. If there is a "badly performing" pattern, we should change it. On a related note I am not strictly happy with Yara's performance at all.

**Comment by QKaiser** [comment]
Yara scanning timed out on 15 files out of > 400.000 files during testing (setup: 4 cores, 16GB memory, but yara probably use a single process). I'll investigate which rules on which exact files triggered this and if a small increase in timeout value would fix it or not.

I'd like to fix it without increasing the timeout value, because at this point timeouts only happens on 0.00375% of our corpus.

**Comment by QKaiser** [comment]
Another possibility, as mentioned by @vlaci would be to just get rid of the timeout. We know for a fact that it's highly unlikely scan time will be higher than 60 seconds for our own usage, but if an unblob user wants to scan a 256GB full disk image they can go at it.

**Comment by vlaci** [comment]
I mean, if we properly indicate the processing progress, the user can decide if they willing to wait for however long or kill it, At the end of the day, a limited total allowed processing time makes sense but we already have the `timeout` command for that.
