### ISSUE TITLE
We should stop using UnkownChunk for matched structures with invalid headers

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#21]
Right now we return an UnknownChunk for any YARA match where its handler failed to compute a ValidChunk. This can be due to YARA matching on something that is not an archive format, the archive header being corrupted, etc.

To me, an unknown chunk should represent chunks in-between valid chunks for which we did not match. We should not emit structures for something that our handlers failed to process.

This can be problematic when running unblob on a 2.5Gb ISO image of Ubuntu. We will have a valid ISO9660 chunk, followed by hundreds of UnknownChunk being printed out on the console. Mostly "fake" ZIP files in my case.

My solution would be to simply return `None` when a format handler cannot properly identify a chunk.

**Comment by kissgyorgy** [comment]
I will do this tomorrow when we merged https://github.com/IoT-Inspector/unblob/pull/40
