### ISSUE TITLE
fix_permissions trips on unresolvable symlinks

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#217]
So, mistake of the day !

`fix_permissions` will try to chmod dangling symlinks, which triggers a `FileNotFoundError` from pathlib (quite obvious in retrospect).

We can fix the code this way:

```python
for path in outdir.rglob("*"):
    if path.is_symlink() and not path.resolve().exists():
        continue
    if path.is_dir():
        path.chmod(0o775)
    else:
        path.chmod(0o664)
```

**Comment by vlaci** [comment]
Do we even need to resolve them? Cannot we just skip symlinks altogether?

**Comment by kukovecz** [comment]
https://docs.python.org/3/library/pathlib.html#pathlib.Path.chmod  - `Path.chmod` has a default `follow_symlinks=True` parameter, which can be turned off. It might help?

**Comment by vlaci** [comment]
Janos's solution seems to be the most correct. On most systems, symlink permission doesn't matter but according to a quick read there are Unices where it does...

**Comment by QKaiser** [comment]
> Do we even need to resolve them? Cannot we just skip symlinks altogether?

We can ! If they point to a file within the extraction directory, it will be chmod'ed anyway.
