### ISSUE TITLE
ZIP handler is miscalculating the end offset if sub-chunks contains a ZIP chunk

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#220]
## Context

Running unblob on a Netgear firmware which is a ZIP archive holding a vendor image partly made of a squashfs filesystem and a release notes file leads to a very weird situation.

Here's the ZIP content:

```
unzip -l /mnt/host/R6700v3-V1.0.4.120_10.0.91.zip
Archive:  /mnt/host/R6700v3-V1.0.4.120_10.0.91.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 47222842  2021-09-16 06:58   R6700v3-V1.0.4.120_10.0.91.chk
      875  2021-09-16 07:02   R6700v3-V1.0.4.120_10.0.91_Release_Notes.html
---------                     -------
 47223717                     2 files
```

Here's a visualization of identified chunks:

![chunk_calculation (1)](https://user-images.githubusercontent.com/569494/151946008-cd0da09e-a891-411d-97e9-642835748265.png)

**inner chunks**:
- `0x0-0x5eba6d` - beginning of ZIP file, ends too early due to wrong calculation ?
- `0x20be0e-0x2d08e0e` - squashfsv4 filesystem section within the vendor image file (`R6700v3-V1.0.4.120_10.0.91.chk`)
- `0x2d09076-0x2d09336` - end of ZIP file, holds release note (`R6700v3-V1.0.4.120_10.0.91_Release_Notes.html`)

**unknown_chunks**:
- `0x5eba6d-0x20be0e` -> end of first valid chunk up to start of second valid chunk (! **start_offset > end_offset**)
- `0x2d08e0e-0x2d09076`

## Issues

1. ZIP handler calculation is wrong and should be investigated
2. We need to explicitly define the behavior of `remove_inner_chunk` and `calculate_unknown_chunks` when we have overlapping chunks

**Comment by martonilles** [comment]
!239 has some draft  fix for this

**Comment by QKaiser** [comment]
The issue here is that we have this hierarchy: `ZIP -> SQUASHFS -> ZIP`, and our handler is matching on the EOCD marker of the zip within the squashfs filesystem rather than the overall ZIP. Simply searching for an EOCD marker and considering it the end of our zip chunk is wrong and misleading.

I have a local branch that fix this while making it more efficient (using `seek` rather than `seek`), will create a PR sometime today.
