### ISSUE TITLE
squshfs extract fails on device files when running as a user

### ISSUE THREAD

**Issue by martonilles** [IoT-Inspector/unblob#250]
When extracting a squashfs as a non root user unsquash fails with permission error if the filesystem includes device nodes/files.

**Comment by martonilles** [comment]
Other alternative is to use fakeroot, either within unblob, or maybe better to run unblobl using fakeroot

**Comment by QKaiser** [comment]
Well either:
1. the user wants to emulate the extracted firmware and care about block devices, char devices, FIFOs, and sockets being created 
2. the user just want to extract the firmware to read actual files content

For option 1 the user must run as root, for option 2 we might as well just use the `-ig` option. We have other extractors that do not create block/char/fifo/socket devices if they lack root privileges without complaining (jefferson, unromfs) :)
