### ISSUE TITLE
Add an option to enable forced overwrite

### ISSUE THREAD

**Issue by martonilles** [IoT-Inspector/unblob#255]
Maybe it is only required testing, but it is really annoying when I extract a firmware and want to extract it again (maybe with a different settings) and I need to remember to delete the files prior to re-extracting it

**Comment by kukovecz** [comment]
I would this to / after #243

**Comment by kukovecz** [comment]
> I would this to / after #243

Since that issue was rescheduled later, we can implement this right now. This looks like a low hanging fruit with small effort to be done, but adds a great benefit of usability.
