### ISSUE TITLE
Binary name requirement of 7-Zip is misleading/inconsistent

### ISSUE THREAD

**Issue by vlaci** [IoT-Inspector/unblob#258]
We use the command `7z` which refers to the `p7zip` port of 7-Zip but we require the original which is either named `7zz` or `7zzs`. We also rename the binary ourselves when we are installing it to docker. It'd be better if we could pickup either `7zz` or `7zzs` as well.

**Comment by QKaiser** [comment]
We should have the ability to dynamically detect whether `7zz` or `7zzs` is installed on the system and use the one that is actually installed when calling 7zip in our handlers.
