### ISSUE TITLE
tar extracts PaxHeaders as a directory from posix archives

### ISSUE THREAD

**Issue by martonilles** [IoT-Inspector/unblob#269]
Since 74e4c998bf1e5bfb55369be1e63dce0446d2a474 extra meta files are extracted from posix tar archives

for example in the integration tests
```
tests/integration/archive/tar/__output__/cherry.gnu.tar_extract/0-81920.tar_extract/banana.gnu.tar_extract/0-30720.tar_extract/apple.posix.tar_extract/0-10240.tar_extract/PaxHeaders/apple1.txt
tests/integration/archive/tar/__output__/cherry.gnu.tar_extract/0-81920.tar_extract/banana.gnu.tar_extract/0-30720.tar_extract/apple.posix.tar_extract/0-10240.tar_extract/PaxHeaders/apple2.txt
```

These are not real files and should not be extracted as files, rather later reported as meta-data

**Comment by QKaiser** [comment]
If we take that decision, we should also filter our `[SYSTEM]` meta-data files from NTFS extraction (see https://github.com/IoT-Inspector/unblob/issues/195).
