### ISSUE TITLE
lz4 compressed linux kernel chunk detection fails

### ISSUE THREAD

**Issue by martonilles** [IoT-Inspector/unblob#360]
Some old linux kernels (ARM 4.X) are using lz4 legacy compression. See https://manpages.debian.org/testing/lz4/unlz4.1.en.html (-l option) for details. However there is no end magic after the compressed content, but could be detected as except the last block all blocks are 8MB uncompressed.

The vmlinx-to-elf project (https://github.com/marin-m/vmlinux-to-elf/issues/27) had a similar bug and has a work-around as well:
https://github.com/marin-m/vmlinux-to-elf/blob/master/vmlinux_to_elf/utils/lz4_legacy.py

**Comment by QKaiser** [comment]
Happy to look into this as I worked on LZ4, can you share a sample with me ?
