### ISSUE TITLE
Add unar in Github Workflows

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#50]
We should add the `unar `dependency to our Github workflow definition in a separate branch and then rebase on it in branches that requires it.

Currently done in the RAR branch (see https://github.com/IoT-Inspector/unblob/pull/33/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957f).

But will be required by PR #33 and #51.

Doing it separately will make the history cleaner I think.

**Comment by kissgyorgy** [comment]
RAR branch is merged.
