### ISSUE TITLE
Refactor Chunk related functions

### ISSUE THREAD

**Issue by kissgyorgy** [IoT-Inspector/unblob#61]
We don't return `UnknownChunk`s from `search_chunks_by_priority` and we don't use the base `Chunk` model anymore, so we can get rid of the abstraction.

**Comment by kukovecz** [comment]
I don't think we should get rid of it. I think having this minimal abstraction layer  like `Chunk` / `UnknownChunk` would help implementing things like #44

**Comment by kissgyorgy** [comment]
I meant the `Chunk` class, which is not used anywhere anymore.

**Comment by kissgyorgy** [comment]
I'm working on it, there are a couple of more precise type hints and small changes needed.
