### ISSUE TITLE
RomFS extractor

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#66]
RomFS filesystem format is not handled by 7zip and there is no standalone extractor on the market. That means we need to mount the filesystem somewhere, copy its content to our output directory, and then unmount the filesystem.

This is what most automated tools do (e.g. [uClinux extract-romfs](https://github.com/rhuitl/uClinux/blob/master/bin/extract-romfs) ).

This is a problem because mount **requires root privileges**.

This is what a naive implementation would do:

```bash
mkdir -p ${outdir}
mkdir -p "${outdir}_tmp"
sudo mount -o loop -t romfs ${infile} "${outdir}_tmp"
cp "${outdir}_tmp"/* ${outdir}/
sudo umount "${outdir}_tmp"
```

We need to either:
- write our own standalone extractor
- find a way to mount cleanly without elevated privileges (udisksctl and the like)
- not support RomFS
- sandbox it

**Comment by vlaci** [comment]
Possible 3rd party tool https://github.com/NikAleksandrov/romfser 
It has a GPL license, so we'd need to segregate it from our code but we could call as a CLI. Need some packaging work to use though.

**Comment by kissgyorgy** [comment]
RomFS specification: https://www.kernel.org/doc/html/latest/filesystems/romfs.html

**Comment by kissgyorgy** [comment]
I vote for writing our own, put it into the https://github.com/IoT-Inspector/unblob/tree/main/unblob/extractors folder and install it via console scripts mechanism (`[tool.poetry.scripts]`)

**Comment by flukavsky** [comment]
I think I remember using this once in a previous life... But also GPL2:
https://github.com/JordanMilne/romfsck2

**Comment by QKaiser** [comment]
See https://github.com/IoT-Inspector/unblob/pull/163
