### ISSUE TITLE
Don't read the whole file into the memory when carving out chunks

### ISSUE THREAD

**Issue by kissgyorgy** [IoT-Inspector/unblob#74]
We are currently reading the whole file into memory when carving out chunks, which is obviously terrible. There is a function for that in standard library: `shutil.copyfileobj`, we should use that instead.

**Comment by kukovecz** [comment]
Reanmed the issue - leaving out the `shutil.copyfileobj`  from the name.  According to its [documentation](https://docs.python.org/3/library/shutil.html#shutil.copyfileobj) this will not be good for us.

Its code copy-pasted from `shutil`
```python
def copyfileobj(fsrc, fdst, length=0):
    """copy data from file-like object fsrc to file-like object fdst"""
    # Localize variable access to minimize overhead.
    if not length:
        length = COPY_BUFSIZE
    fsrc_read = fsrc.read
    fdst_write = fdst.write
    while True:
        buf = fsrc_read(length)
        if not buf:
            break
        fdst_write(buf)
```

We have a big blob of file and we want to carve out a chunk with X size from it. This function can only copy the whole file. 

So, I am doing a really simple implementation into our `file_utils.py`.

**Comment by kissgyorgy** [comment]
> This function can only copy the whole file.

It can copy only part of the file if you seek in it first, but you are right that it doesn't take account the `end_offset` we need.
