### ISSUE TITLE
Use Git LFS to store integration test files

### ISSUE THREAD

**Issue by kissgyorgy** [IoT-Inspector/unblob#75]
There are some file formats which would be too big to commit in the Git repo. We need to generate these files or Use Git-LFS for these: https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

- [x] FAT 32
- [x] Apple DMG format on Mac OS X

Or just use Git LFS for ALL the integration test files.

**Comment by kissgyorgy** [comment]
A couple of notes:
- The full git history needs to be rewritten to track `tests/integration`
- There is a 1GB limit for free usage when using Git LFS (should be enough, but we should still not go crazy with big files)
- git LFS needs to be installed on developer machines (should not be a problem?)
- rebase for existing branches might be hard (we don't have a lot of open branches now, so it's an ideal time to covert the repo)

**Comment by QKaiser** [comment]
Let's move to LFS and we can still recreate the two branches that have open pull requests if rebasing is too difficult.

**Comment by kissgyorgy** [comment]
The LFS migration is ready, README has to be updated and we can add the big files now.

**Comment by QKaiser** [comment]
See https://github.com/IoT-Inspector/unblob/pull/80
