### ISSUE TITLE
Support out-of-tree extensions for handling additional file formats

### ISSUE THREAD

**Issue by vlaci** [IoT-Inspector/unblob#96]
_As a security researcher, I need a quick way to add support additional extractors, so that I can analyze currently unsupported firmware images._

An extension is just a Python file stored in a well-known and-or configurable location that should be picked-up without any hassle.

**Comment by martonilles** [comment]
I would also consider how to make it easier to provide detection rules and extraction code. Currently it is a bit of extra work to attach an extractor also in many cases detection and extraction might share additional data (already detected by the handler) or code to parse/process some format.

**Comment by martonilles** [comment]
- Might not need priorities between handlers (yara callbacks could also make priorities less useful)
- Could create pirorities based on handler type (eg: fs, compression, etc.)
